services:
  market-pro-frontend:
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    container_name: market-pro-frontend
    env_file:
      - .env.local
    ports:
      - "5173:5173"
    networks:
      - market-pro
networks:
  market-pro:
    name: market-pro
